import { Handler } from '@netlify/functions';
import pg from 'pg';

const { Client } = pg;

// PROD DB 연결 정보
const connectionString = 'postgresql://postgres:5Go7aHutmffqk8Je@db.mkoryudscamnopvxdelk.supabase.co:5432/postgres';

export const handler: Handler = async (event) => {
    const client = new Client({
        connectionString,
    });

    try {
        await client.connect();

        const sql = `
            -- 테이블 생성: site_links (운영 환경 스키마에 최적화)
            CREATE TABLE IF NOT EXISTS public.site_links (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                url TEXT NOT NULL,
                description TEXT,
                image_url TEXT,
                category TEXT,
                created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
                is_approved BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
            );

            -- RLS 활성화
            ALTER TABLE public.site_links ENABLE ROW LEVEL SECURITY;

            -- 정책 초기화 (중복 방지용 삭제)
            DROP POLICY IF EXISTS "승인된 사이트 모음은 누구나 볼 수 있습니다." ON public.site_links;
            DROP POLICY IF EXISTS "관리자는 모든 사이트 모음을 볼 수 있습니다." ON public.site_links;
            DROP POLICY IF EXISTS "로그인한 사용자는 사이트 모음을 등록할 수 있습니다." ON public.site_links;
            DROP POLICY IF EXISTS "작성자 또는 관리자는 사이트 모음을 수정할 수 있습니다." ON public.site_links;
            DROP POLICY IF EXISTS "작성자 또는 관리자는 사이트 모음을 삭제할 수 있습니다." ON public.site_links;

            -- 정책 1: 누구나 승인된 항목만 조회 가능
            CREATE POLICY "승인된 사이트 모음은 누구나 볼 수 있습니다." 
            ON public.site_links FOR SELECT 
            USING (is_approved = true);

            -- 정책 2: 관리자는 모든 항목 조회 가능 (board_admins 테이블 참조)
            CREATE POLICY "관리자는 모든 사이트 모음을 볼 수 있습니다." 
            ON public.site_links FOR SELECT 
            USING (
              EXISTS (SELECT 1 FROM public.board_admins WHERE user_id = auth.uid())
            );

            -- 정책 3: 가입된 사용자는 항목 등록 가능
            CREATE POLICY "로그인한 사용자는 사이트 모음을 등록할 수 있습니다." 
            ON public.site_links FOR INSERT 
            WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = created_by);

            -- 정책 4: 작성자 본인 또는 관리자만 수정 가능
            CREATE POLICY "작성자 또는 관리자는 사이트 모음을 수정할 수 있습니다." 
            ON public.site_links FOR UPDATE 
            USING (
              auth.uid() = created_by OR
              EXISTS (SELECT 1 FROM public.board_admins WHERE user_id = auth.uid())
            );

            -- 정책 5: 작성자 본인 또는 관리자만 삭제 가능
            CREATE POLICY "작성자 또는 관리자는 사이트 모음을 삭제할 수 있습니다." 
            ON public.site_links FOR DELETE 
            USING (
              auth.uid() = created_by OR
              EXISTS (SELECT 1 FROM public.board_admins WHERE user_id = auth.uid())
            );

            -- 인덱스 추가
            CREATE INDEX IF NOT EXISTS idx_site_links_is_approved ON public.site_links(is_approved);
            CREATE INDEX IF NOT EXISTS idx_site_links_created_at ON public.site_links(created_at DESC);
        `;

        await client.query(sql);

        return {
            statusCode: 200,
            body: JSON.stringify({ success: true, message: 'Table site_links created and policies applied.' }),
        };
    } catch (err: any) {
        return {
            statusCode: 500,
            body: JSON.stringify({ success: false, error: err.message }),
        };
    } finally {
        await client.end();
    }
};
