import pg from 'pg';
const { Client } = pg;

const connectionString = 'postgresql://postgres:postgres@127.0.0.1:54322/postgres';

const client = new Client({
    connectionString,
});

async function runSQL() {
    try {
        await client.connect();
        console.log('Connected to local DB');

        const sql = `
        CREATE TABLE IF NOT EXISTS public.site_links (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            url TEXT NOT NULL,
            description TEXT,
            image_url TEXT,
            category TEXT,
            created_by UUID,
            is_approved BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
        `;

        await client.query(sql);
        console.log('site_links table created successfully.');

        // Add policies just in case
        await client.query(`
            ALTER TABLE public.site_links ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS "누구나 승인된 사이트를 조회할 수 있다" ON public.site_links;
            CREATE POLICY "누구나 승인된 사이트를 조회할 수 있다" ON public.site_links FOR SELECT USING (is_approved = true);
            DROP POLICY IF EXISTS "관리자는 모든 사이트 조회/관리 가능" ON public.site_links;
            CREATE POLICY "관리자는 모든 사이트 조회/관리 가능" ON public.site_links USING (auth.jwt() ->> 'email' IN ('clown313joy@gmail.com', 'linda.lindyhop@gmail.com', 'jess.sujin.jeon@gmail.com'));
            DROP POLICY IF EXISTS "인증된 사용자는 사이트를 등록할 수 있다" ON public.site_links;
            CREATE POLICY "인증된 사용자는 사이트를 등록할 수 있다" ON public.site_links FOR INSERT TO authenticated WITH CHECK (true);
            DROP POLICY IF EXISTS "사용자는 자신이 등록한 항목을 삭제할 수 있다" ON public.site_links;
            CREATE POLICY "사용자는 자신이 등록한 항목을 삭제할 수 있다" ON public.site_links FOR DELETE USING (auth.uid() = created_by);
            DROP POLICY IF EXISTS "사용자는 자신이 등록한(승인 대기) 항목을 조회할 수 있다" ON public.site_links;
            CREATE POLICY "사용자는 자신이 등록한(승인 대기) 항목을 조회할 수 있다" ON public.site_links FOR SELECT USING (auth.uid() = created_by);
        `);
        console.log('Policies applied successfully.');

    } catch (e) {
        console.error('Error:', e);
    } finally {
        await client.end();
    }
}

runSQL();
