CREATE TABLE IF NOT EXISTS user_notification_preferences (
  user_id VARCHAR(64) NOT NULL PRIMARY KEY,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  pref_today_digest TINYINT(1) NOT NULL DEFAULT 1,
  pref_new_event_alerts TINYINT(1) NOT NULL DEFAULT 0,
  pref_events TINYINT(1) NOT NULL DEFAULT 1,
  pref_class TINYINT(1) NOT NULL DEFAULT 1,
  pref_clubs TINYINT(1) NOT NULL DEFAULT 1,
  pref_new_event_social TINYINT(1) NOT NULL DEFAULT 1,
  pref_new_event_class TINYINT(1) NOT NULL DEFAULT 1,
  pref_new_event_clubs TINYINT(1) NOT NULL DEFAULT 1,
  pref_filter_tags_json LONGTEXT NULL,
  pref_filter_class_genres_json LONGTEXT NULL,
  pref_digest_time CHAR(5) NOT NULL DEFAULT '08:30',
  pref_digest_days_json VARCHAR(64) NOT NULL DEFAULT '[0,1,2,3,4,5,6]',
  pref_digest_timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Seoul',
  pref_only_with_events TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY user_notification_preferences_enabled_idx (enabled, pref_today_digest, pref_new_event_alerts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
