-- 1. Add 'anonymous' category and adjust display order
INSERT INTO public.board_categories (name, code, icon, display_order, is_active)
VALUES ('익명게시판', 'anonymous', 'ri-user-secret-line', 2, true)
ON CONFLICT (code) DO UPDATE 
SET display_order = 2, is_active = true;

-- Adjust display order for other categories
UPDATE public.board_categories 
SET display_order = display_order + 1 
WHERE display_order >= 2 AND code != 'anonymous';

-- 2. Update board_posts table
-- Add dislikes column
ALTER TABLE public.board_posts 
ADD COLUMN IF NOT EXISTS dislikes integer DEFAULT 0;

-- Update check_category constraint
ALTER TABLE public.board_posts 
DROP CONSTRAINT IF EXISTS check_category;

ALTER TABLE public.board_posts 
ADD CONSTRAINT check_category 
CHECK (category IN ('free', 'trade', 'notice', 'market', 'anonymous', 'dev-log'));

-- Add display_order column for manual sorting
ALTER TABLE public.board_posts 
ADD COLUMN IF NOT EXISTS display_order integer DEFAULT 0;

-- 3. Create board_post_dislikes table
CREATE TABLE IF NOT EXISTS public.board_post_dislikes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, -- Optional for anonymous
    post_id bigint REFERENCES public.board_posts(id) ON DELETE CASCADE NOT NULL,
    fingerprint text, -- For anonymous dislike limiting
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, post_id),
    UNIQUE(fingerprint, post_id)
);

-- Enable RLS
ALTER TABLE public.board_post_dislikes ENABLE ROW LEVEL SECURITY;

-- Policies for dislikes
CREATE POLICY "Dislikes are viewable by everyone"
    ON public.board_post_dislikes FOR SELECT
    USING ( true );

CREATE POLICY "Anyone can insert dislikes"
    ON public.board_post_dislikes FOR INSERT
    WITH CHECK ( true );

-- 4. Create board_banned_words table
CREATE TABLE IF NOT EXISTS public.board_banned_words (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word text UNIQUE NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.board_banned_words ENABLE ROW LEVEL SECURITY;

-- Policies for banned words
CREATE POLICY "Banned words are viewable by everyone"
    ON public.board_banned_words FOR SELECT
    USING ( true );

CREATE POLICY "Only admins can manage banned words"
    ON public.board_banned_words FOR ALL
    USING ( (SELECT is_admin_user()) )
    WITH CHECK ( (SELECT is_admin_user()) );

-- 5. Auto-hide posts with 10+ dislikes
-- Create function
CREATE OR REPLACE FUNCTION public.check_post_dislikes()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT count(*) FROM public.board_post_dislikes WHERE post_id = NEW.post_id) >= 10 THEN
        UPDATE public.board_posts SET is_hidden = true WHERE id = NEW.post_id;
    END IF;
    -- Also update the dislikes count in board_posts
    UPDATE public.board_posts 
    SET dislikes = (SELECT count(*) FROM public.board_post_dislikes WHERE post_id = NEW.post_id)
    WHERE id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger
DROP TRIGGER IF EXISTS tr_check_post_dislikes ON public.board_post_dislikes;
CREATE TRIGGER tr_check_post_dislikes
AFTER INSERT ON public.board_post_dislikes
FOR EACH ROW EXECUTE FUNCTION public.check_post_dislikes();

-- 6. Trigger for likes count sync (Missing in original schema maybe?)
CREATE OR REPLACE FUNCTION public.sync_post_likes()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.board_posts 
    SET likes = (SELECT count(*) FROM public.board_post_likes WHERE post_id = NEW.post_id)
    WHERE id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_sync_post_likes ON public.board_post_likes;
CREATE TRIGGER tr_sync_post_likes
AFTER INSERT OR DELETE ON public.board_post_likes
FOR EACH ROW EXECUTE FUNCTION public.sync_post_likes();

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
