-- Create social_group_favorites table
CREATE TABLE IF NOT EXISTS public.social_group_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES public.social_groups(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, group_id)
);

-- Add RLS Policies
ALTER TABLE public.social_group_favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Favorites are viewable by everyone" ON public.social_group_favorites
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own favorites" ON public.social_group_favorites
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites" ON public.social_group_favorites
    FOR DELETE USING (auth.uid() = user_id);
