-- 1. Create board_post_favorites table
CREATE TABLE IF NOT EXISTS public.board_post_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES public.board_posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, post_id)
);

-- 2. Add favorites count column to board_posts
ALTER TABLE public.board_posts 
ADD COLUMN IF NOT EXISTS favorites INTEGER DEFAULT 0;

-- 3. Migration: Copy existing likes to favorites (Preserve data for Star icon)
INSERT INTO public.board_post_favorites (user_id, post_id, created_at)
SELECT user_id, post_id, created_at FROM public.board_post_likes
ON CONFLICT DO NOTHING;

-- 4. Update favorites count based on migrated data
UPDATE public.board_posts
SET favorites = likes;

-- 5. Reset Likes (Heart) for fresh start
TRUNCATE TABLE public.board_post_likes;
UPDATE public.board_posts SET likes = 0;

-- 6. Create Trigger to auto-update favorites count
CREATE OR REPLACE FUNCTION public.update_post_favorites_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.board_posts
        SET favorites = favorites + 1
        WHERE id = NEW.post_id;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.board_posts
        SET favorites = favorites - 1
        WHERE id = OLD.post_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_board_post_favorite_change ON public.board_post_favorites;
CREATE TRIGGER on_board_post_favorite_change
AFTER INSERT OR DELETE ON public.board_post_favorites
FOR EACH ROW EXECUTE FUNCTION public.update_post_favorites_count();

-- 7. Add RLS Policies for board_post_favorites
ALTER TABLE public.board_post_favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Favorites are viewable by everyone" ON public.board_post_favorites
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own favorites" ON public.board_post_favorites
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites" ON public.board_post_favorites
    FOR DELETE USING (auth.uid() = user_id);

-- 8. Ensure board_post_likes RLS is correct (just in case)
ALTER TABLE public.board_post_likes ENABLE ROW LEVEL SECURITY;
-- (Assuming existing policies are fine, but good to double check or re-apply if needed, usually mostly same as favorites)
