-- Create board_post_likes table
create table if not exists public.board_post_likes (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    post_id bigint references public.board_posts(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, post_id)
);

-- Enable RLS
alter table public.board_post_likes enable row level security;

-- Policies
create policy "Likes are viewable by everyone"
    on public.board_post_likes for select
    using ( true );

create policy "Users can insert their own likes"
    on public.board_post_likes for insert
    with check ( auth.uid() = user_id );

create policy "Users can delete their own likes"
    on public.board_post_likes for delete
    using ( auth.uid() = user_id );

-- Create index for faster lookups
create index if not exists board_post_likes_user_id_idx on public.board_post_likes(user_id);
create index if not exists board_post_likes_post_id_idx on public.board_post_likes(post_id);
