-- Recreate board_prefixes table to remove hidden dependencies on 'users' table
-- This is a cleaner schema-based solution than using Security Definer functions.

-- 1. Rename existing table to backup (just in case)
ALTER TABLE board_prefixes RENAME TO board_prefixes_backup;

-- 2. Create the new table CLEANLY (Only necessary columns)
CREATE TABLE board_prefixes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    color text,
    admin_only boolean DEFAULT false,
    display_order int DEFAULT 0,
    board_category_code text REFERENCES board_categories(code) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now()
);

-- 3. Copy existing data
INSERT INTO board_prefixes (id, name, color, admin_only, display_order, board_category_code, created_at)
SELECT id, name, color, admin_only, display_order, board_category_code, created_at
FROM board_prefixes_backup;

-- 4. Restore Index
CREATE INDEX idx_board_prefixes_category_clean ON board_prefixes(board_category_code);

-- 5. Enable RLS
ALTER TABLE board_prefixes ENABLE ROW LEVEL SECURITY;

-- 6. Clean Policies (Using board_admins as requested)
CREATE POLICY "Allow admin full access" ON board_prefixes
    FOR ALL
    USING (
        auth.uid() IN (SELECT user_id FROM board_admins)
    );

CREATE POLICY "Allow public read" ON board_prefixes
    FOR SELECT USING (true);

-- 7. Grant Permissions to roles
GRANT ALL ON board_prefixes TO authenticated;
GRANT ALL ON board_prefixes TO service_role;
GRANT ALL ON board_prefixes TO postgres;
GRANT USAGE ON SEQUENCE board_prefixes_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE board_prefixes_id_seq TO service_role;
