-- Create webzine_posts table
create table if not exists public.webzine_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  content jsonb not null,
  cover_image text,
  author_id uuid references auth.users not null,
  is_published boolean default false,
  views integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.webzine_posts enable row level security;

-- Create policies
create policy "Public can read published posts"
on public.webzine_posts for select
using ( is_published = true );

create policy "Admins can do everything"
on public.webzine_posts for all
using (
  auth.uid() in ( select user_id from board_admins )
  or
  (select get_user_admin_status()) = true
);

-- Grant access to authenticated users (needed for insertion by admins logged in as authenticated)
grant all on public.webzine_posts to authenticated;
grant select on public.webzine_posts to anon;
