CREATE TABLE IF NOT EXISTS public.swing_oneday_recruit_link_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id text NOT NULL,
  action text NOT NULL CHECK (action IN ('insert', 'update', 'delete')),
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_email text,
  changed_fields text[],
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.swing_oneday_recruit_link_audit_logs
DROP CONSTRAINT IF EXISTS swing_oneday_recruit_link_audit_logs_link_id_fkey;

CREATE INDEX IF NOT EXISTS swing_oneday_recruit_link_audit_logs_link_idx
ON public.swing_oneday_recruit_link_audit_logs (link_id, created_at DESC);

CREATE INDEX IF NOT EXISTS swing_oneday_recruit_link_audit_logs_actor_idx
ON public.swing_oneday_recruit_link_audit_logs (actor_user_id, created_at DESC);

ALTER TABLE public.swing_oneday_recruit_link_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Oneday recruit edit logs readable by owner or admin" ON public.swing_oneday_recruit_link_audit_logs;
CREATE POLICY "Oneday recruit edit logs readable by owner or admin"
ON public.swing_oneday_recruit_link_audit_logs
FOR SELECT
TO authenticated
USING (actor_user_id = auth.uid() OR public.is_admin_user());

GRANT SELECT ON public.swing_oneday_recruit_link_audit_logs TO authenticated;
GRANT ALL ON public.swing_oneday_recruit_link_audit_logs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.swing_oneday_recruit_link_audit_logs_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.audit_oneday_recruit_link_changes()
RETURNS trigger AS $$
DECLARE
  v_claims jsonb := '{}'::jsonb;
  v_before jsonb;
  v_after jsonb;
  v_changed_fields text[];
BEGIN
  -- Service-role jobs/functions can write explicit audit rows with the validated actor.
  IF auth.role() = 'service_role' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  BEGIN
    v_claims := COALESCE(NULLIF(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb);
  EXCEPTION WHEN others THEN
    v_claims := '{}'::jsonb;
  END;

  IF TG_OP = 'INSERT' THEN
    v_after := to_jsonb(NEW);
    v_changed_fields := ARRAY(SELECT jsonb_object_keys(v_after) ORDER BY 1);
  ELSIF TG_OP = 'UPDATE' THEN
    v_before := to_jsonb(OLD);
    v_after := to_jsonb(NEW);

    SELECT array_agg(field_name ORDER BY field_name)
    INTO v_changed_fields
    FROM (
      SELECT jsonb_object_keys(v_before || v_after) AS field_name
    ) fields
    WHERE field_name <> 'updated_at'
      AND COALESCE(v_before -> field_name, 'null'::jsonb)
        IS DISTINCT FROM COALESCE(v_after -> field_name, 'null'::jsonb);

    IF COALESCE(array_length(v_changed_fields, 1), 0) = 0 THEN
      RETURN NEW;
    END IF;
  ELSIF TG_OP = 'DELETE' THEN
    v_before := to_jsonb(OLD);
    v_changed_fields := ARRAY(SELECT jsonb_object_keys(v_before) ORDER BY 1);
  END IF;

  INSERT INTO public.swing_oneday_recruit_link_audit_logs (
    link_id,
    action,
    actor_user_id,
    actor_email,
    changed_fields,
    before_data,
    after_data
  ) VALUES (
    COALESCE(NEW.id, OLD.id),
    lower(TG_OP),
    auth.uid(),
    NULLIF(v_claims ->> 'email', ''),
    v_changed_fields,
    v_before,
    v_after
  );

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS audit_oneday_recruit_link_changes ON public.swing_oneday_recruit_links;
CREATE TRIGGER audit_oneday_recruit_link_changes
AFTER INSERT OR UPDATE OR DELETE ON public.swing_oneday_recruit_links
FOR EACH ROW
EXECUTE FUNCTION public.audit_oneday_recruit_link_changes();

DROP POLICY IF EXISTS "Public can insert oneday recruit links during test" ON public.swing_oneday_recruit_links;
DROP POLICY IF EXISTS "Public can update oneday recruit links during test" ON public.swing_oneday_recruit_links;
DROP POLICY IF EXISTS "Authenticated users can insert oneday recruit links" ON public.swing_oneday_recruit_links;
DROP POLICY IF EXISTS "Authenticated users can update oneday recruit links" ON public.swing_oneday_recruit_links;
DROP POLICY IF EXISTS "Admins can delete oneday recruit links" ON public.swing_oneday_recruit_links;

CREATE POLICY "Authenticated users can insert oneday recruit links"
ON public.swing_oneday_recruit_links
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can update oneday recruit links"
ON public.swing_oneday_recruit_links
FOR UPDATE
TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can delete oneday recruit links"
ON public.swing_oneday_recruit_links
FOR DELETE
TO authenticated
USING (public.is_admin_user());

REVOKE INSERT, UPDATE, DELETE ON public.swing_oneday_recruit_links FROM anon;
GRANT SELECT ON public.swing_oneday_recruit_links TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.swing_oneday_recruit_links TO authenticated;
GRANT ALL ON public.swing_oneday_recruit_links TO service_role;
