-- Create board_post_views table (mirrors board_post_likes structure)
CREATE TABLE IF NOT EXISTS public.board_post_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    fingerprint TEXT,
    post_id BIGINT REFERENCES public.board_posts(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- One view per user OR fingerprint per post
    CONSTRAINT unique_user_post_view UNIQUE NULLS NOT DISTINCT (user_id, post_id),
    CONSTRAINT unique_fingerprint_post_view UNIQUE NULLS NOT DISTINCT (fingerprint, post_id),
    
    -- Ensure either user_id or fingerprint is provided
    CONSTRAINT check_user_or_fingerprint CHECK (
        (user_id IS NOT NULL AND fingerprint IS NULL) OR 
        (user_id IS NULL AND fingerprint IS NOT NULL)
    )
);

-- Enable RLS
ALTER TABLE public.board_post_views ENABLE ROW LEVEL SECURITY;

-- Policies (same pattern as board_post_likes)
CREATE POLICY "Views are viewable by everyone"
    ON public.board_post_views FOR SELECT
    USING (true);

CREATE POLICY "Anyone can insert views"
    ON public.board_post_views FOR INSERT
    WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS board_post_views_user_id_idx ON public.board_post_views(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS board_post_views_fingerprint_idx ON public.board_post_views(fingerprint) WHERE fingerprint IS NOT NULL;
CREATE INDEX IF NOT EXISTS board_post_views_post_id_idx ON public.board_post_views(post_id);
