-- 1. Add missing columns to board_posts
ALTER TABLE public.board_posts 
ADD COLUMN IF NOT EXISTS likes integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS dislikes integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS display_order integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS password text;

-- 1.1 Add missing columns to board_comments
ALTER TABLE public.board_comments 
ADD COLUMN IF NOT EXISTS password text;

-- 1.2 Make user_id nullable for board_comments (for anonymous comments)
ALTER TABLE public.board_comments ALTER COLUMN user_id DROP NOT NULL;

-- 2. Update category constraint
ALTER TABLE public.board_posts DROP CONSTRAINT IF EXISTS check_category;
ALTER TABLE public.board_posts ADD CONSTRAINT check_category 
CHECK (category IN ('free', 'trade', 'notice', 'market', 'anonymous', 'dev-log'));

-- 3. Ensure anonymous category exists and adjust orders (Anonymous = 2)
UPDATE public.board_categories SET display_order = display_order + 1 WHERE display_order >= 2 AND code != 'anonymous';
INSERT INTO public.board_categories (name, code, display_order, is_active)
VALUES ('익명게시판', 'anonymous', 2, true)
ON CONFLICT (code) DO UPDATE 
SET name = '익명게시판', display_order = 2, is_active = true;

-- 4. Create board_post_dislikes table
CREATE TABLE IF NOT EXISTS public.board_post_dislikes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    post_id bigint REFERENCES public.board_posts(id) ON DELETE CASCADE NOT NULL,
    fingerprint text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, post_id),
    UNIQUE(fingerprint, post_id)
);

-- Enable RLS
ALTER TABLE public.board_post_dislikes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Dislikes are viewable by everyone" ON public.board_post_dislikes;
CREATE POLICY "Dislikes are viewable by everyone" ON public.board_post_dislikes FOR SELECT USING ( true );
DROP POLICY IF EXISTS "Anyone can insert dislikes" ON public.board_post_dislikes;
CREATE POLICY "Anyone can insert dislikes" ON public.board_post_dislikes FOR INSERT WITH CHECK ( true );

-- 5. Create board_banned_words table
CREATE TABLE IF NOT EXISTS public.board_banned_words (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word text UNIQUE NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.board_banned_words ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Banned words are viewable by everyone" ON public.board_banned_words;
CREATE POLICY "Banned words are viewable by everyone" ON public.board_banned_words FOR SELECT USING ( true );

-- 6. Trigger for auto-hide & sync (Dislikes)
CREATE OR REPLACE FUNCTION public.check_post_dislikes()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT count(*) FROM public.board_post_dislikes WHERE post_id = NEW.post_id) >= 10 THEN
        UPDATE public.board_posts SET is_hidden = true WHERE id = NEW.post_id;
    END IF;
    UPDATE public.board_posts 
    SET dislikes = (SELECT count(*) FROM public.board_post_dislikes WHERE post_id = NEW.post_id)
    WHERE id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_check_post_dislikes ON public.board_post_dislikes;
CREATE TRIGGER tr_check_post_dislikes AFTER INSERT ON public.board_post_dislikes FOR EACH ROW EXECUTE FUNCTION public.check_post_dislikes();

-- 7. Trigger for likes sync
CREATE OR REPLACE FUNCTION public.sync_post_likes()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.board_posts 
    SET likes = (SELECT count(*) FROM public.board_post_likes WHERE post_id = COALESCE(NEW.post_id, OLD.post_id))
    WHERE id = COALESCE(NEW.post_id, OLD.post_id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_sync_post_likes ON public.board_post_likes;
CREATE TRIGGER tr_sync_post_likes AFTER INSERT OR DELETE ON public.board_post_likes FOR EACH ROW EXECUTE FUNCTION public.sync_post_likes();

-- 8. RLS Policies for board_comments
ALTER TABLE public.board_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Comments are viewable by everyone" ON public.board_comments;
CREATE POLICY "Comments are viewable by everyone" ON public.board_comments 
FOR SELECT USING ( true );

DROP POLICY IF EXISTS "Anyone can insert comments" ON public.board_comments;
CREATE POLICY "Anyone can insert comments" ON public.board_comments 
FOR INSERT WITH CHECK ( true );

DROP POLICY IF EXISTS "Users can update own comments" ON public.board_comments;
CREATE POLICY "Users can update own comments" ON public.board_comments 
FOR UPDATE USING ( auth.uid() = user_id OR password IS NOT NULL );

DROP POLICY IF EXISTS "Users can delete own comments" ON public.board_comments;
CREATE POLICY "Users can delete own comments" ON public.board_comments 
FOR DELETE USING ( auth.uid() = user_id OR password IS NOT NULL );

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
